name: "Sync Upstream"
on:
  schedule:
    - cron: '1 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: 0xHx
          base: master
          head: master